<?php

namespace App\Exports;

use App\Models\Backend\County;                                                                                                                                  
use Maatwebsite\Excel\Concerns\FromCollection;

class CountyExport implements FromCollection
{                                                                                                                                                                                                                                                                                                                                                   
    /**
    * @return \Illuminate\Support\Collection
    */
    public function collection()
    {
        return County::all();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
    }                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
}
